#Based on template from: https://github.com/ThreeDeeJay/GitHub-Actions-build-templates/blob/main/Windows-CMake.yml
name: Build

env:
  GH_TOKEN: ${{github.token}}
  Branch: ${{github.ref_name}}
  Platform: x64
  Configuration: Release
  Artifacts: build/Release
  Title: ${{github.event.repository.name}}
  DXSDK_DIR: C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\

on:
  push:
    Branches: $Branch
  pull_request:
    Branches: $Branch
  workflow_dispatch:

jobs:
  Windows:
    runs-on: windows-2022
    steps:

    - name: Clone repo and submodules
      run: git clone https://${{github.repository_owner}}:${{github.token}}@github.com/${{github.repository}}.git "${{github.workspace}}" --branch ${{env.Branch}} --recurse-submodules

    - name: Get current date, commit hash and count
      run: |
        echo "FirstCommitHash=$(git rev-list --max-parents=0 HEAD --first-parent)" >> $env:GITHUB_ENV
        echo "CommitHash=$(git rev-parse HEAD)" >> $env:GITHUB_ENV
        echo "CommitHashShort=$(git rev-parse --short=7 HEAD)" >> $env:GITHUB_ENV
        echo "CommitCount=$(git rev-list --count HEAD)" >> $env:GITHUB_ENV
        echo "CommitDate=$(git show -s --date=format:'%Y-%m-%d' --format=%cd)" >> $env:GITHUB_ENV

    - name: Cache DirectX SDK
      id: DXSDK_Jun10
      uses: actions/cache@v4
      with:
        path: ${{env.DXSDK_DIR}}
        key: DXSDK_Jun10
    - name: Install DirectX SDK
      if: steps.DXSDK_Jun10.outputs.cache-hit != 'true'
      shell: powershell
      run: |
        Invoke-WebRequest -Method Get -Uri https://download.microsoft.com/download/a/e/7/ae743f1f-632b-4809-87a9-aa1bb3458e31/DXSDK_Jun10.exe -OutFile DXSDK_Jun10.exe -UseBasicParsing
        Start-Process -Wait ./DXSDK_Jun10.exe -ArgumentList "/U"
    - name: Set DXSDK_DIR
      run: echo "DXSDK_DIR=C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\" >> $env:GITHUB_ENV

    - name: Install Dependencies
      run: |
        curl -L "https://raw.githubusercontent.com/NVIDIA/nvapi/refs/heads/main/nvapi.h" -o "include/nvapi/nvapi.h" --create-dirs

    - name: Configure
      run: cmake -A "${{env.Platform}}" -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.Configuration}} #-DCMAKE_PREFIX_PATH=vcpkg\installed\x64-windows

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.Configuration}}

    - name: List files
      run: ls -R

    - name: Upload artifacts to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: "${{env.Title}}_r${{env.CommitCount}}@${{env.CommitHashShort}}"
        path: "${{github.workspace}}/${{env.Artifacts}}/"

    - name: Compress artifacts
      if: github.event_name == 'push'
      run: |
        mkdir Release
        7z a "Release/${{env.Title}}.zip" "${{github.workspace}}/${{env.Artifacts}}/*" -mx=9
        cp "Release/${{env.Title}}.zip" "Release/${{env.Title}}_r${{env.CommitCount}}@${{env.CommitHashShort}}.zip"

    - name: Purge tag - latest-${{env.Branch}}
      if: github.event_name == 'push'
      run: |
        gh release delete latest-${{env.Branch}} --repo ${{github.repository}} --cleanup-tag --yes || true

    - name: Release - archive-${{env.Branch}}
      if: github.event_name == 'push'
      run: |
        gh release create archive-${{env.Branch}} --repo ${{github.repository}} --target ${{env.FirstCommitHash}} --latest=false --prerelease --title "${{env.Title}} ${{env.Branch}} build archive" --notes "Latest build: https://github.com/${{github.repository}}/releases/latest-${{env.Branch}}
        Build logs: https://github.com/${{github.repository}}/actions" || true
        gh release edit archive-${{env.Branch}} --repo ${{github.repository}} --target ${{env.FirstCommitHash}} --latest=false --prerelease --title "${{env.Title}} ${{env.Branch}} build archive" --notes "Latest build: https://github.com/${{github.repository}}/releases/latest-${{env.Branch}}
        Build logs: https://github.com/${{github.repository}}/actions" || true
        gh release upload archive-${{env.Branch}} --repo ${{github.repository}} --clobber "Release/${{env.Title}}_r${{env.CommitCount}}@${{env.CommitHashShort}}.zip"

    - name: Release - latest-${{env.Branch}}
      if: github.event_name == 'push'
      run: |
        gh release create latest-${{env.Branch}} --repo ${{github.repository}} --target ${{env.CommitHash}} --generate-notes --latest=true --title "${{env.Title}} r${{env.CommitCount}}@${{env.CommitHashShort}}" --notes "Build archive: https://github.com/${{github.repository}}/releases/tag/archive-${{env.Branch}}
        Build log: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
        gh release upload latest-${{env.Branch}} --repo ${{github.repository}} --clobber "Release/${{env.Title}}.zip"
